wandb_version: 1

epochs:
  desc: null
  value: 10
dataset:
  desc: null
  value: mnist
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.17.1
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1718091272
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      - 105
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      - 105
      3:
      - 2
      - 7
      - 16
      - 23
      - 38
      4: 3.8.16
      5: 0.17.1
      8:
      - 1
      - 2
      - 4
      - 5
      13: darwin-arm64
    m:
    - 1: epoch/epoch
      6:
      - 3
    - 1: epoch/loss
      5: 1
      6:
      - 1
    - 1: epoch/accuracy
      5: 1
      6:
      - 1
    - 1: epoch/val_loss
      5: 1
      6:
      - 1
    - 1: epoch/val_accuracy
      5: 1
      6:
      - 1
    - 1: epoch/learning_rate
      5: 1
      6:
      - 1
